---
# tasks file for mqtt

- name: Create mqtt data directory
  ansible.builtin.file:
    path: "{{ mqtt_path_datadir }}"
    state: directory
    mode: "0755"

- name: Create a mqtt Quadlet
  notify: Reload systemd daemon
  containers.podman.podman_container:
    name: "{{ __mqtt_container_name }}"
    image: "{{ mqtt_container_image }}"
    command:
      - mosquitto
      - -c
      - /mosquitto-no-auth.conf
    state: quadlet
    device: "/dev/sda:/dev/xvda:rwm"
    ports: "{{ __mqtt_container_ports }}"
    volumes: "{{ __mqtt_container_volumes }}"
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=newer"
      - |
        [Install]
        WantedBy=default.target

- name: Invoke handlers
  ansible.builtin.meta: flush_handlers

- name: Start MQTT service
  ansible.builtin.systemd:
    name: "{{ __mqtt_container_name }}"
    state: started
    enabled: true

- name: Enable mosquitto ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 2181/tcp
    - 2888/tcp
    - 3888/tcp
